<?php

/**
 * @file
 * Synchronize files for a Content Type with an Amazon S3 bucket.
 */

/**
 * Implements hook_views_data().
 */
function amazon_s3_sync_views_data() {
  $table = array(
    'amazon_s3_sync_files' => array(
      'table' => array(
        'group' => 'Amazon S3 sync',
        'base' => array(
          'title' => 'Amazon S3 storage',
          'help' => 'List of Amazon S3 synced files.',
          'field' => 'id',
        ),
      ),
      'id' => array(
        'title' => 'ID',
        'help' => '',
        'field' => array(
          'id' => 'numeric',
        ),
        'filter' => array(
          'id' => 'numeric',
        ),
        'sort' => array(
          'id' => 'standard',
        ),
        'argument' => array(
          'id' => 'numeric',
        ),
      ),
      'fid' => array(
        'title' => 'User ID',
        'help' => 'The user ID.',
        'field' => array(
          'id' => 'numeric',
        ),
        'filter' => array(
          'id' => 'numeric',
        ),
        'sort' => array(
          'id' => 'standard',
        ),
        'argument' => array(
          'id' => 'numeric',
        ),
        'relationship' => array(
          'base' => 'file_managed',
          'base field' => 'fid',
          'id' => 'standard',
          'label' => 'file',
        ),
      ),
      'created' => array(
        'title' => 'Created',
        'help' => 'The time that the file was synced to Amazon S3.',
        'field' => array(
          'id' => 'date',
        ),
        'filter' => array(
          'id' => 'date',
        ),
        'sort' => array(
          'id' => 'date',
        ),
      ),
      'modified' => array(
        'title' => 'Modified',
        'help' => 'The time that the updated was synced on Amazon S3.',
        'field' => array(
          'id' => 'date',
        ),
        'filter' => array(
          'id' => 'date',
        ),
        'sort' => array(
          'id' => 'date',
        ),
      ),
    ),
    'file_managed' => array(
      'table' => array(
        'group' => 'file',
      ),
      'filename' => array(
        'title' => 'Filename',
        'help' => 'Appears in: file.',
        'field' => array(
          'id' => 'standard',
        ),
        'filter' => array(
          'id' => 'string',
        ),
        'sort' => array(
          'id' => 'standard',
        ),
        'argument' => array(
          'id' => 'string',
        ),
      ),
    ),
  );

  return $table;
}
